resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: vijay
      path: vijayreddy1991/pipelines-testing
      branches:
        include: main
pipelines:
  - name: P_WF_pipelines
    configuration:
      integrations:
        - name: vijay_generic
        - name: vijay
    steps:
      - name: P_WF_step1
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
        execution:
          onExecute:
            - pwd
            - echo $int_vijay_generic_test



        

