resources:
  - name: git_repo
    type: GitRepo
    configuration:
      gitProvider: ankit
      path: vijayreddy1991/pipelines-testing
      branches:
        include: main
pipelines:
  - name: P_WF_pipelines
    configuration:
      integrations:
        - name: ank_generic
        - name: ankit
    steps:
      - name: P_WF_step1
        type: Bash
        configuration:
          inputResources:
            - name: git_repo
        execution:
          onExecute:
            - pwd
            - echo $int_ank_generic_test



        

